// <auto-generated />
using System;
using Auth.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auth.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240229161247_fix2")]
    partial class fix2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("Auth.Models.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countrys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fdee5e4e-4d81-437d-81b1-a21c29e5c5c1"),
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("6ba78be0-f9ae-4b70-9513-eefaf0cbbf99"),
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("0c0537f1-36d3-4e05-acfb-5ab8de111216"),
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("93d112cc-5af6-4090-a5d5-1196a366c01d"),
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("580cf5af-4f7b-4dd9-953d-4d085d34da21"),
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("ad36273d-dbf0-4e66-8894-8bda940d6bd0"),
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("8260d86f-669d-4224-944f-538e624550c6"),
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("73535048-ef94-41fb-af93-7db372f7d11e"),
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("5625745e-604f-400b-93fb-e842bc2d43a0"),
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("a7cc3913-22be-4f9a-b6a3-6ac885d1c8a4"),
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("3223edde-8106-42e1-a8db-6a037e17e933"),
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("433b33f9-736e-4ccc-9bcc-e5a4ae3676a7"),
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("16dfd0d3-19b9-438b-9d98-4b0debc37767"),
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("bda2bf16-8cc5-4bc3-a441-4d84b66bd83a"),
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("d655bca4-d615-4b9f-ae88-ba74247d6ae6"),
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("dd8306b1-9739-49f9-ac3c-5ea354a492c9"),
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("0fc9f8b5-59a8-46a3-a834-1ce892011cff"),
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("87703806-d779-4c36-8891-ab7355a295cb"),
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("3228b6fc-6a2e-45f5-a8e2-2fca115243b4"),
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("41bc91e2-3820-4e3f-a809-cf1b96dba324"),
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("95d0f453-8b5d-4cc7-a1ea-34afdc8217d4"),
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("d700cb49-204c-4a31-97ef-1302e0244bcb"),
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("c4e10f04-7abd-4ba9-89c7-b4d8b666bc91"),
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("ca05323c-b699-414e-9b1a-8b94dff8557f"),
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("d0569788-1e84-4256-b995-e9b032fd3c35"),
                            Code = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("ea7c81b4-6c4f-4a7a-83e5-cf3402724f12"),
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("49399363-0ba8-4ca9-bcc8-cf7f2885a526"),
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("76420fe7-26ca-4bbb-80ef-74fdb1ba169c"),
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("4db5beee-0613-43d5-b019-e4ce0c94fcac"),
                            Code = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("c530008b-1e14-4af4-bffc-b22b1b7738da"),
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("69d9936d-0ff3-49ec-94a4-89822052483b"),
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("81e9a5bb-5cf8-4df8-91f8-57d7961e0125"),
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("7f139d99-547e-4bef-9561-f5c5df848071"),
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("ca9c1f0a-be13-46a1-b2e9-18475c2e8de2"),
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("889f9438-0ced-4066-ba65-133ef7c28a5f"),
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("34b935a7-3f77-4005-8df9-8a7dc27f11f4"),
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("fb6c9894-46b1-41bc-8757-b557b5dbe050"),
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("cafd31b3-0c16-4d20-9758-4068778c1e4d"),
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("d44732a4-a8d4-4738-b9b4-53d593eb6309"),
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("be298f2f-4ce2-4448-8ba2-aa33e1506d3b"),
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("4226b064-06fd-43de-a5ac-1485c4ddd089"),
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("c0d8bc9f-b5e4-4c73-aaff-842268d000d2"),
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("4ba77a6c-a3d2-4f5d-8131-1a99adebaae1"),
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("827fdf81-94b0-4d70-b76f-625cb7f3edb4"),
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("f6d8f2b0-bd9b-4396-89e8-a33e514e1651"),
                            Code = "CD",
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = new Guid("0fb76a28-d38d-490e-b36d-e39cbefd3035"),
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("d90764da-7cb2-4990-b5db-669f9e19e850"),
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("67b8e1d2-a668-47d2-a11b-6083e3f94009"),
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("2f260ee8-8719-4cf4-80cb-27e49b7cd0b4"),
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("b96051eb-d163-4282-9ac3-f62c01009457"),
                            Code = "TL",
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = new Guid("0254fb3f-bbf7-45db-a860-aef4ef64adc0"),
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("569a25e4-3df8-40e7-b0e5-e41dd526ee60"),
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("2970ec51-4bbc-47e8-b3aa-fb0bec098015"),
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("e4bef3dc-fb21-4dc9-9ce6-221aa7f89cad"),
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("dacf4c5c-a1dd-4768-a510-a230024cfc6e"),
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("5247474f-793e-41c5-8dbd-005a020b9722"),
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("cd534993-8c86-4831-b6ed-2bfd6179a644"),
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("71748fff-96c8-4656-a140-9b58ae181195"),
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("d71c5b34-d29f-4036-a333-9d92e1cd56fa"),
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("fbe1aae9-6ed2-4933-9431-46c5a3cc46af"),
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("b68cf697-4006-4d88-9cbb-55e6cabb5480"),
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("09029b1f-4b6c-4a79-afc2-a6a19c33caaf"),
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("fc0cb8d3-fe36-4e67-ba8d-d9200ab38698"),
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("bdd6744b-9c46-477c-859d-699110b0c45d"),
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("0da0415f-46f5-46b2-b287-f4aaa60f9b14"),
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("fa1142fb-0e6d-490b-af1e-2709ccba4089"),
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("a4d5000e-dbe0-4400-9d73-ef92b55220e6"),
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("10525995-93bb-407d-8942-9fbcb6821c77"),
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("4881ac96-35f8-4630-a859-b9782f751060"),
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("6d5c7ff2-9c98-4823-8e88-cb50b3e4bee2"),
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("d8d4cd19-a6c7-410a-aa4a-3351e1e2b0c4"),
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("a7a73652-2607-4044-b985-027ed4328aca"),
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("b7c7bd02-826a-434c-bebf-a47737d7d9d6"),
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("83cbb6c8-52b0-4a72-9ee1-cd7391b3bede"),
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("59786a6b-41be-4c74-a245-d24ab98094e3"),
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("023e182c-1bc9-4fec-97eb-f6944fe043a0"),
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("0c6dad0f-6d72-45ec-a471-c8d45c34dc57"),
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("f164ea7c-41d1-4f49-a08a-2be356bca34e"),
                            Code = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = new Guid("dfa86c2b-0742-49ed-ab4a-7a25ed8c1c05"),
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("163a3a35-f7a7-411b-b7c8-e0adbd15aadd"),
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("fcdb8db2-f1ed-4aa0-b072-ac522377073d"),
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("7bb05b13-a46e-4b9b-8e35-8119cea71e08"),
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("70572cb1-32d8-42cd-ad6c-0d077ed9628c"),
                            Code = "CI",
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = new Guid("f275763b-bdc9-445e-aaa6-a9e6d3d0d8ff"),
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("344dd832-85f4-475c-9ba8-ce41e167c4a6"),
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("05f758d0-788d-47ef-a195-f1a984836235"),
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("c87559b4-a192-46cd-9026-f4c3c09968e1"),
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("22f9b039-d6b5-4ea8-98eb-eb6806bf836a"),
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("ca5fcb4c-506e-43c7-a6a8-ad7144dfe48d"),
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("0742ef81-6e6d-4171-97c6-2abebac182e7"),
                            Code = "XK",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("c8702dde-e61c-4e5d-8ae0-6feca2c4301e"),
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("bc17dc15-ff30-4d90-8bae-d5ffe5126c5b"),
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("a0bb51fa-4ce4-4b65-b4e0-31339b1d4ec0"),
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("84b1d361-e8c0-44be-9643-ce25f8739458"),
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("925439e5-43f8-483d-bbf1-a59c1317c9fc"),
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("cc82c597-e192-415c-8833-1956764588d0"),
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("f8c868b8-4498-4cba-a1ee-cd8710a15679"),
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("57b29522-904e-47db-83c4-d8c08908b126"),
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("9b8c2c69-c915-4bb2-95dd-f417523a13af"),
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("d5729a38-51f7-40b0-b7f1-89c61485ecaa"),
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("2a0a19cd-8c08-423b-ac96-8ec7733defa6"),
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("88039e45-df14-4765-b239-e2b44c374e7b"),
                            Code = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("2ccf16e4-9dfc-4e7d-8719-3111f9efe9f7"),
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("e4aac013-df75-4523-8c06-9351d86dc9c1"),
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("a5e8a658-f4dd-4a1d-94b4-9ae6dfd40569"),
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("0d4eb002-d091-4a78-b5b7-f19d0ead16b4"),
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("9ed0bcba-43b5-427c-a6b2-5b9db05bfbe9"),
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("53d4c151-8268-436b-bb9b-c6a878e34c08"),
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("49e1b7c4-dbbb-4501-95fb-9d1c00915ed5"),
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = new Guid("eebf03e2-c681-44f6-bcd0-b9f339ba1559"),
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("8134bf85-256f-4a8d-8512-ac86317f6b36"),
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("78db7135-cfe0-4412-bc3f-411e80108a13"),
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("a381ed83-0064-461a-b7fb-42761f121a40"),
                            Code = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = new Guid("49a06ccd-c0fe-48a2-9f25-006516edd9df"),
                            Code = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = new Guid("02b8efae-8ab7-4a4e-82b8-f46a5682b859"),
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("0bc6fabc-550e-4449-aad6-0bbfc719d608"),
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("8d037b84-8164-402a-9983-277643f172c3"),
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("4cd47fca-b693-4590-8db5-e03b98dbcf97"),
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("879dac91-14ab-4670-a728-044bad38f15c"),
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("a5f08839-5403-4f04-be9a-a3a8db941d2e"),
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("fc71c4a0-5532-49d8-8864-702bd719d712"),
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("5fe258ae-be15-431e-a0eb-d0b84aa14143"),
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("7e519fde-10e9-47df-834c-471ed87a385b"),
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("d8ab25fd-8eca-4c24-bc83-37136ec93533"),
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("d8dd622c-1e51-49e4-a935-186a5c46b4f9"),
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("3da34636-9ccd-4caf-aded-4d61bbe8f4fd"),
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("89319628-d523-4a10-9955-4fed113df36f"),
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("caa1cd55-1a9d-47f8-97c9-cf9a68edb927"),
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("de14d547-7f09-4642-8caf-518c2f8b3034"),
                            Code = "KP",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = new Guid("3fe6191e-0beb-4fe3-b983-569a0191b534"),
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("fd0df0ce-1c87-40f5-802a-91be812cc694"),
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("a0eaf04f-f717-4405-9bb5-62bb2291926f"),
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("6476cea6-8bbc-4303-84d5-0a638e94d6e4"),
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("016d8b24-3ac3-492e-8c49-b19527f66637"),
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("99ebda29-1fea-4c14-a565-f7e593c34951"),
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("cef0d136-9077-4fb1-85b2-ad519e4be903"),
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("0fa2ede7-22b8-4594-bbdc-66a40946278f"),
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("799f2eab-f94f-4967-bf6d-44d30de6dae5"),
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("ab6b8dab-8889-4ac3-98fc-1b8482e56746"),
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("7220a5e4-7f29-4f80-9965-d2d72e1e90dc"),
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("b9fefd95-e386-41f7-b87d-d0a81cf320dc"),
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("856dd149-c285-4548-be01-1f1d58ec0a17"),
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("4764530a-2965-4b48-9b6e-68e20d36eb91"),
                            Code = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("d3720b96-b4df-4efd-a0fb-b83c4cec0eb3"),
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("0d960056-679c-4710-97c1-0cc4ccd1ff79"),
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("cc344bde-d830-4627-8aef-fec1ddd623a4"),
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("abfbd69c-48a6-46a6-9f49-793922274736"),
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("60fab896-e47f-47e6-8103-03fd58fb18fb"),
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("0306feba-193f-4251-9a20-7e7ecc9e207f"),
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("6d017f45-1ee5-40ec-86f4-adeb0866caf7"),
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("59ab13c3-97c8-4115-a195-ca381e1d7471"),
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("f46772a4-e5d7-4772-9811-bbecf746e60d"),
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("8e633a27-5fe2-4bca-8375-cfabae0d2a4a"),
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("c3e71909-d990-43c7-87f4-d9db78eed94e"),
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("3a8a9e23-0af8-4540-8c31-ec1c2e4a4639"),
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("c3897635-27a4-485d-b632-62db20a65292"),
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("700c5bdd-cd7a-4225-8fff-3ccffb6b8347"),
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("1510a94b-56cf-4948-9d37-147d8587737b"),
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("42d7ef45-9b5e-4ab3-b2ab-130e16cd45d2"),
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("4cb7ff4c-5242-419d-a545-5391dad35978"),
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("2613ab91-797d-4bbd-aa68-ae86a6c6674b"),
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("1ce8bb73-ec60-476c-afcc-dd66206f1dcd"),
                            Code = "KR",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("ae040777-13a0-4d06-a07f-d3a8b7ce492e"),
                            Code = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("c965a25d-5252-497f-bb62-7c53a5cb94bf"),
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("b41dd650-5233-4196-8fda-3bffddebecef"),
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("9afada4c-8deb-4a28-8a01-da84c4a23103"),
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("ae4318c1-83a7-4d99-8c57-7b16c3e500c6"),
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("d84cb0a5-2b18-461a-bad9-f003d2299d50"),
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = new Guid("59c37593-3253-4ef6-8847-caceec08d2dc"),
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("12fe46a7-7cea-4c9d-ab6c-243150fd7efe"),
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("53ccafe5-4440-4996-913c-face7bdfc933"),
                            Code = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = new Guid("e567a7b9-953e-4f4b-956c-9dbf03bf1f2e"),
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = new Guid("573248e0-fb06-4cc8-9994-68edf177c86d"),
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("2954dd7d-90f6-4f05-b431-73b84e4cca79"),
                            Code = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("c0e0fd92-7b72-4912-9abf-1b4fc772f2c8"),
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("55882c60-a18b-44b3-b4f7-7aca055e026d"),
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("62743c5c-13e9-4058-915a-a0cfdaa289aa"),
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("c2b2f5c7-6984-4c86-8003-bfdeaed8a11d"),
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("94188736-bd60-4003-bdcc-6d5cb5579983"),
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("17139f8b-ddfe-4623-88a2-bba60a00f39d"),
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("715a31e6-13d5-4d89-bb9b-2a1f02b341e4"),
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("3f08e5bd-5bbf-4cf0-85e8-adf2b4cefa1d"),
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("0acc9eae-79b0-42e9-a5ff-8cd04274e46d"),
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("f5817a51-c695-44af-9fae-0faa91865a9e"),
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("93f3607e-3cb8-4da4-8ddf-88c9454a66e9"),
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("3be94490-b629-4f91-adb8-d1ddf1e1e6df"),
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("d105cd68-8c1e-41cc-8758-706bbbb8eb57"),
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("5d71badc-9ea8-45c7-8e0a-1fac61a98fb1"),
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("504ea9dc-0341-49e2-99bc-7972590e584a"),
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("eb3642b7-e463-4819-a6db-001a20651023"),
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("cce68efd-f2e4-4387-affe-7b2d6669ad17"),
                            Code = "VA",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = new Guid("c13e04a7-b91b-47f9-aad1-2c511ad5bbed"),
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("275c370c-cf0c-4339-9e19-25417e9dd572"),
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("2385e661-eee9-478a-ab15-c2b66ee91323"),
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("45f668ed-83a8-4286-8656-e72812e91f7a"),
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("e84ba78f-3ece-430a-bd0e-5796b8e42aa7"),
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Auth.Models.Models.Friendship", b =>
                {
                    b.Property<Guid>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecieverId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.HasKey("FriendshipId");

                    b.HasIndex("RecieverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Auth.Models.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Auth.Models.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("UserImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("CountryId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Auth.Models.Models.Friendship", b =>
                {
                    b.HasOne("Auth.Models.Models.User", "Reciever")
                        .WithMany("Friendships2")
                        .HasForeignKey("RecieverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Models.Models.User", "Sender")
                        .WithMany("Friendships1")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reciever");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Auth.Models.Models.Notification", b =>
                {
                    b.HasOne("Auth.Models.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.Models.Models.User", b =>
                {
                    b.HasOne("Auth.Models.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Auth.Models.Models.User", b =>
                {
                    b.Navigation("Friendships1");

                    b.Navigation("Friendships2");
                });
#pragma warning restore 612, 618
        }
    }
}
