// <auto-generated />
using System;
using Auth.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auth.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("Auth.Models.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countrys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09104a69-d7fb-4e9c-982a-9b6c87ea166e"),
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("8f3f64a3-cab4-4256-947e-45ee58c14bb4"),
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("f41062ce-e35d-40c4-b8dd-c687ef465a07"),
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("de5ee6ee-a20a-4cc2-bd64-27dd9c8d8f33"),
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("f38751ed-e649-4ceb-8ba3-91e4d2beecd1"),
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("695d5ded-dac3-4641-a738-b4792acf7939"),
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("066216ff-069e-4975-bf70-822e49a33fab"),
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("0eda96bc-4f00-445a-a1b9-1eb61086bbfe"),
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("e64db3d3-a1e8-4f23-aeb6-d70e19d727d2"),
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("11c20290-b31d-48fb-8771-2ed8e5347a87"),
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("f822c6a8-d6da-434d-a1cb-318680e701b3"),
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("c00e3f3b-b6f0-4fbf-b658-7d1ac543d5ef"),
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("4bfeb007-0ccd-4592-9662-2c7666aa50ae"),
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("64728739-2b4c-4405-8374-7de7f3053f1d"),
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("0cf93641-c335-42ed-a5ce-7c5822844e48"),
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("b016bb85-75b9-4dd1-b6ec-eae8bf370e20"),
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("f34ff7e9-ef09-432d-97b2-017659f85696"),
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("19cbae87-39fe-4523-b301-12bb57558f67"),
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("7a950fd3-688e-46c3-86de-c79aaffb58f0"),
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("f0aebe7a-bf1e-4e44-8b98-d85c94e8edb2"),
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("6f4cc9c5-c28f-47db-a439-906289f59fe1"),
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("782b845e-9e47-4dc1-98ce-a30e3062a175"),
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("20793634-f22e-458b-aa33-949a41873ba9"),
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("42b9325e-b7e4-4215-9ff1-82511a3d8e0a"),
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("9ab3c8e6-6dd5-498e-b592-660e5c5d3585"),
                            Code = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("efccd6a3-d477-4470-9f5a-afbd371ebb70"),
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("96010ab5-58e4-4666-bea0-4a14b4c8fbac"),
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("ac3469d4-24aa-4217-b4f1-6c9d1a3d0ee6"),
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("57f07c42-55d8-4feb-9048-35a46c419bab"),
                            Code = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("ecdf39fa-a3b9-4d7f-9b37-bba97c4628b3"),
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("bdc582fc-5fea-483a-add5-86ff5e82530f"),
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("d494a5a4-8fbb-4083-9d54-a9ea5282ffed"),
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("ae136ab0-682c-4314-8c39-4de288fba15c"),
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("9746ebe6-003d-40bb-a008-84b10c2d3cc1"),
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("4faf6eb6-168c-4a80-89f6-18ee16d42d07"),
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("56c0dfa7-475d-427f-b2d8-19b0ac5fbd76"),
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("6ce95312-c86d-4321-aa80-39c056746bec"),
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("0449c296-83d3-4f42-912d-398fddfeac8f"),
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("a42a08e0-9a5e-499c-8c98-974ef8923585"),
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("b5ebb884-af5b-4ea9-a61c-bf824fb0d3e4"),
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("1a1a545d-179e-4c78-9f83-69664c4482ee"),
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("ddfbda1a-a15f-4f33-96a9-aa4dcf9add56"),
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("bbce2a0b-6f87-4cbc-a71a-177b3969bc4f"),
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("f778a4d2-f81f-40c5-a9a1-d451b8593414"),
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("25b7d2f8-c3be-4116-b830-c368abb894d9"),
                            Code = "CD",
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = new Guid("29fdc335-8f5d-4329-be00-29157fa17005"),
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("7372b0b6-dbec-456b-8f1f-9156009fb34c"),
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("2fd8ed6a-da57-433c-b40f-b5e68b7ae593"),
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("1bc8bc12-e20f-47c4-b3e3-7247d02effc9"),
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("eecf38f3-a478-4c1d-a860-5daed6e65a49"),
                            Code = "TL",
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = new Guid("eb905af3-6d63-4cbd-a7cc-e8342f35d8c3"),
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("96881418-7bcf-4f59-a050-e93e135a2455"),
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("3f9241b5-8175-490e-a0a6-e9fefe342541"),
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("2c3aca89-97bd-444c-8489-71b0977eba73"),
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("35a4b155-6555-467f-ba48-21049ae52a4f"),
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("669d7c97-01a2-402a-9a28-625144184a66"),
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("b6f6d48b-10a5-4fee-9e7b-963ddd7d8296"),
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("f48a101d-30c0-4a00-afc8-a6737c4d0e02"),
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("8f11f361-d301-4468-bcfa-6d784674c1fb"),
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("28097201-622e-480b-a36c-d123b9685c14"),
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("e14ab7c4-44c8-4bdc-8c3d-d6cd883c6ccd"),
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("e820e9a2-8617-481e-9600-fdcecb085f94"),
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("ea9e562c-96e5-4cb4-ae5f-374ef41e9da3"),
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("148f37c2-c406-47ec-9e8d-05fa995c4f59"),
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("bb76f743-29ce-4693-9b61-b648cb5d5d48"),
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("315eb608-841f-4c93-8188-3fe7ee20e7e2"),
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("1216569d-999a-4e38-893e-5c7ed1e08c52"),
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("e5298e4c-d95c-417b-af11-0dca1da3827b"),
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("9997dac7-a2ee-495d-886e-f746a0942dc9"),
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("776e2c8d-baee-42e1-89f7-5433a10b2c5a"),
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("ca761c6c-07a2-4069-a437-1c87e33d677e"),
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("2869e019-7e81-4257-93ac-2f168d301c00"),
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("34170a48-6c5a-4b2b-ba47-8aa0514c0e8d"),
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("1a3dffde-2285-48af-9013-6503ea68a71b"),
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("f85ee678-2376-4e9f-b239-63637b7ad645"),
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("d0d90eff-ae52-4ef3-943e-486b037143a5"),
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("215edeed-aea1-4f60-967b-c8b7f5375fa6"),
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("03a22155-7891-4101-b1cd-f11dcac1403d"),
                            Code = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = new Guid("444ea099-ee0d-4540-b8c3-0668f7b2218f"),
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("fa1d0fa9-364b-4142-8181-0233a4970e82"),
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("66395865-ad31-417c-a8e0-8e6cfc174ea3"),
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("cecd4386-e176-4d4e-a589-012ea3ecd5d3"),
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("f0007d5c-8a94-4a18-879b-5531323e654f"),
                            Code = "CI",
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = new Guid("2554f087-dffc-4af6-bc01-4122f4630d52"),
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("03a1cd41-7394-4c33-804b-50f3ae63afb9"),
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("cf9dec91-8532-44b8-a225-7a1faa9fad3b"),
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("5c088d38-10cc-4c71-8a96-ddb9983fffdc"),
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("ee10902b-0369-4927-bd6f-3ee3af737cf5"),
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("e8c25baf-048e-42ad-ad0d-2cf3617b427b"),
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("1de59465-22f9-46e3-8489-99ab3e39dfb2"),
                            Code = "XK",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("ebda3f84-ab3c-48ed-8663-fba074dcce12"),
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("8e8ba41c-48c1-4f8a-8db1-d91c476d991b"),
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("707dfe08-71d0-41ff-8b4f-01b5e0775e4a"),
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("4c7122e3-69ba-48e5-8786-72a776dbcf77"),
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("ecbd97e7-1f75-4158-b81a-6f965cb0fea7"),
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("3c65e946-ef88-4849-a8b5-cd92b851cfd5"),
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("b92d0e1c-9e19-41cd-83e2-5976b89a70fc"),
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("94695042-728d-4929-a030-80138dc0dec4"),
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("12caee02-9668-4311-beed-0dd9ff88afc0"),
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("f47927fb-d93e-4904-92dd-1646a2439fc0"),
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("cfd6d428-49be-40d2-874f-ac346ec13b0d"),
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("8f58b1a8-24fb-4a37-9d1a-6bd6a119f26b"),
                            Code = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("fb07e6a8-97c0-47ea-aba9-ea18da04c2cd"),
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("ffcd3ff5-b716-4c56-9c44-27f43ceeb7b7"),
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("14920c52-eb6c-4ca2-933f-083bd2af5b0b"),
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("fa91c2fc-4283-420f-ae17-5957656b5a9a"),
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("7b8075c3-78f0-491b-b4c5-94edf98e5a81"),
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("e9938f66-e8be-48f6-ab0c-ee39f714c331"),
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("1973e9be-46c2-4146-8b09-256e4e45df62"),
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = new Guid("a21be421-9fa3-4fcc-a23e-4fdbf6c696e3"),
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("161a77ef-892a-4aa7-9ee5-648748029283"),
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("16172ea5-f263-4876-b008-750fe5d09f2e"),
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("b50f1783-4a20-4d1a-9ad1-ca68421e41c3"),
                            Code = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = new Guid("d6a5d108-7ca8-43cf-a389-6d0e0154e4c5"),
                            Code = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = new Guid("60817fcd-6f47-47ea-95ab-5a3090fb0584"),
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("4320a8c7-d0bc-480f-9fc6-457e34dac7c0"),
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("7f6e538d-f446-424c-bb67-03f4ee6b4ea2"),
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("a086b9a8-5ba8-4ac9-9c79-c3bfb68258dc"),
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("84bdd035-327e-4624-be06-cabe0003764c"),
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("90fe886b-a33e-4cf5-bed0-aa1792b2eaca"),
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("c4b167f8-689b-4afa-b15d-1eebafeaa278"),
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("26501661-98d3-477f-bc29-8a32e4c8b894"),
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("7b28b2a4-7175-4b64-b415-4313f069400e"),
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("ddbd9dc5-32a4-455c-a598-268c351019a8"),
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("cbe3b0cf-069a-4b62-b679-3cf43d379914"),
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("0edccdc3-bed0-45a5-a886-192d7b0fa2b4"),
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("511bcef4-31ba-4c42-a3b5-bf20890768b5"),
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("8ab2d1aa-7b33-4825-b2a6-e68070e7baf5"),
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("13160ca8-2a18-451b-bc7a-8431a3c8a286"),
                            Code = "KP",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = new Guid("8a275a58-a526-4f20-8e26-0a57c47759a0"),
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("c8c0c072-95ac-4427-8139-9170b44760b7"),
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("9254c4b9-39bb-4ac4-82d7-36842449d655"),
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("90bb2ec4-1040-43af-bfaa-2a013bf6630e"),
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("33c6b6cf-2c2e-4071-9d29-52037c995b6f"),
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("07fd548b-1e1f-4633-a8f0-87f920e10b4d"),
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("0ddda937-f8cf-4d99-ae92-54d2429e7a1b"),
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("735b191d-ccd8-49c6-8f8d-d9b1535e8e18"),
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("84e3b092-548a-40ba-94e4-0a0f7d329c76"),
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("8604d561-e8a5-4e8f-9bd8-6362675cdc97"),
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("11901cc4-93d7-42db-8a6a-a32b71a9e8c0"),
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("890c54f6-a68c-4cb0-85fb-411c341b5229"),
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("20dbf05a-5a71-4800-81ab-c79004b19535"),
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("4e9e1000-4f5f-4d23-9385-bca2ede7e3bd"),
                            Code = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("9f86e555-5376-4439-a9be-4de7d5ad6d7e"),
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("53033a60-adab-4b0c-a83d-3809cb87efe1"),
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("9adea670-6d7c-4e69-ba1e-245be2e9f4f9"),
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("3070ced3-cf6a-4684-abc1-9d6abc62f054"),
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("73ee67fa-f32c-4ce5-8daa-8e1dbaabd4b7"),
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("4ecafc44-e56f-4be0-b29a-87405ab954e8"),
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("c5fac1f0-9b3d-4165-b5a4-b7fa14b2876a"),
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("414113a6-2034-4ae2-8400-eac36e6a2372"),
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("67b2970f-d7e7-4dee-bd52-085533b92523"),
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("dc3c1dd7-7a62-4941-ab08-7bde474b406b"),
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("5dc942be-f099-4c14-8036-c9498ada2e27"),
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("b338ede4-f0a9-4b1a-90cf-c68232668ee8"),
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("8989040f-67ea-418d-b523-a49265131556"),
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("ad5c42e8-7497-44dc-995a-62fe0793d5e7"),
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("7673b4b7-9d33-43f0-8021-16ecfe22b3e5"),
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("97be6b47-805a-4eb5-8f86-8d1ca817328f"),
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("4d0bed98-ab52-4b3b-bb29-e4cd563ec7a9"),
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("28cb6ef3-7bc5-44c0-940a-1a724c7be8cb"),
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("ba062912-aa42-4bcc-96e7-30128dc0d172"),
                            Code = "KR",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("db368883-9d84-4f17-be50-953ad6a7dc47"),
                            Code = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("124addbb-ba46-4919-99b6-819a50126bc6"),
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("26480ef2-e2d8-479e-949c-04894d9f4d6e"),
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("a6ad8c8e-f9aa-430a-9e11-a20ea48e81ec"),
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("1c6d3c57-2dc7-41cf-8ad4-7b682753dd27"),
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("87aabdbd-fc5f-4715-bd58-c65446701798"),
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = new Guid("b97000a6-900c-4e11-8601-1f27629653ed"),
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("5e07949c-a5df-4f90-b6cf-dfe1e9e96865"),
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("1f08153d-c040-4614-8928-d73cd8aadca0"),
                            Code = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = new Guid("38a3b836-276d-4feb-be11-fa69042edeed"),
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = new Guid("28696725-ca38-44e8-8b2d-d6e10f4308e7"),
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("bc28c4be-d669-45eb-909c-cc08ebcc071d"),
                            Code = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("2028e9ca-cfa7-4b10-9a89-f8b2b8b2dad8"),
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("64ceb7c8-145d-4fb5-b207-e83e4b9c1e79"),
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("45ecd397-9ff1-427e-a4bb-51dac9641d28"),
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("551c02fe-5b2f-42e1-abb2-3836620a9c39"),
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("6aaf437f-9322-4981-9ed8-7fa9c948987e"),
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("06ceac33-0109-41fc-8970-f4aaceb64925"),
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("528445a8-4456-49d7-bd7e-5ad5ac01d74f"),
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("6a0c2257-5ddd-429b-bbf1-d3d5dfd386cf"),
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("ce8d1b47-b730-4d6b-b272-69cb28dd6d5a"),
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("d5569361-9881-4fcd-b9dd-80004bca4817"),
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("1500ee0f-ac6b-4c7c-9959-3b418207d55f"),
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("98cca953-9d30-4dcf-bbfd-187b818bc82d"),
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("76ba8598-e5dc-4cec-8cf5-a2959f99e413"),
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("4412fd9b-a902-4626-92f4-3d8882f141e2"),
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("b71512fc-53e2-42f1-a62c-4e7028128709"),
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("a5f44319-c2f8-4c29-9c16-acfe13f7aeda"),
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("fa0408e3-9d39-48fc-b1c3-431e0a42a0a6"),
                            Code = "VA",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = new Guid("fbb221bd-e096-458a-b85b-22d7cc4c19c6"),
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("ed2aeea3-336f-4ffb-ba86-5bab0077b1bf"),
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("44a91fb0-326d-47e1-ba2b-843fbc77dac4"),
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("80a546ab-8c87-4a7a-ae46-db7742431705"),
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("9eb8a667-8019-4dfa-926d-8322a19d6c8d"),
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Auth.Models.Models.Friendship", b =>
                {
                    b.Property<Guid>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecieverId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.HasKey("FriendshipId");

                    b.HasIndex("RecieverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Auth.Models.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("UserImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("CountryId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Auth.Models.Models.Friendship", b =>
                {
                    b.HasOne("Auth.Models.Models.User", "Reciever")
                        .WithMany("Friendships2")
                        .HasForeignKey("RecieverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Models.Models.User", "Sender")
                        .WithMany("Friendships1")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reciever");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Auth.Models.Models.User", b =>
                {
                    b.HasOne("Auth.Models.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Auth.Models.Models.User", b =>
                {
                    b.Navigation("Friendships1");

                    b.Navigation("Friendships2");
                });
#pragma warning restore 612, 618
        }
    }
}
