// <auto-generated />
using System;
using Backgammon_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity_DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231005082206_friendshipUpdate")]
    partial class friendshipUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("Identity_Models.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countrys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0153ee8a-b097-4f74-8761-fb6e67b1d55a"),
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("aed9a41a-fed3-4ad7-a039-6c0560f713c1"),
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("98d34753-1d20-469e-8adb-c403d3964f5f"),
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("eab90498-0fe3-4377-93cd-b571ab1ba499"),
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("e8097d29-00a2-42eb-8ac0-f9b4848a72be"),
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("2f58c674-677e-4991-8b44-1ef9b29a53ee"),
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("4583b1b3-60d7-4a75-b85c-8484aad41a9e"),
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("c99ae041-f13a-4041-8395-f01c30385ba7"),
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("71023389-a83f-499e-851e-579acf524713"),
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("823dc69e-4747-4d38-85ab-172a0ebbce2f"),
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("55682e97-932c-4fcb-86e9-4cfa41550b8b"),
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("b9cf2c3e-6eed-4f56-a739-469fec8615f5"),
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("79dad92a-f49b-4324-8848-1318f380d321"),
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("ff4b3e4f-6425-419b-95e8-92c005d0f763"),
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("6caf66fe-b520-41b5-ad2b-490f175a12a8"),
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("ff7ec182-0826-421f-8347-0bec11ba0abc"),
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("78e773d3-5d48-445d-9a70-26a0105667ff"),
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("a8f799a4-c665-4502-b474-fed2bfaa7e1f"),
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("d5766ff3-3c0d-411d-9579-2269dc7a500c"),
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("9db4d2a3-9e30-4514-bf98-acd2ab023204"),
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("6746cb7a-1da5-42bd-8904-e26f4d4e9e34"),
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("bffcd854-a800-4f54-8e1e-759d6bfe4fa6"),
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("e096ee89-775c-4628-a975-9455a45a8a3a"),
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("8910c3cc-8a0a-4f42-af50-4677804447e0"),
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("33f299ea-fc0e-4c86-99dd-6c4a19479b1e"),
                            Code = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("091914e4-e143-4033-b724-9f1f206073b1"),
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("899f530f-e89e-4ccd-b47b-2ad22b263dbf"),
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("e9628c5e-69d3-4c0b-ac84-bbe3b32253b9"),
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("0a27a654-cfe3-4fb7-9b64-f2b691d7e08f"),
                            Code = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("d527aa54-45a9-495c-a070-01e705a0aa64"),
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("74897edd-ed3f-4213-b51b-0f2d4fedc158"),
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("87c63160-e371-4dc8-b8a6-349da79dee2a"),
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("174e53fe-71cf-43d8-8404-f3f68a562c5f"),
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("7af6078b-8e47-4c92-b6a8-0536b65664bf"),
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("3befff76-170f-4169-8279-8dcefb760f45"),
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("fdbdf1bf-429c-42be-85ab-87f931c5426e"),
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("9d182341-3419-4d3a-b495-fc46c1143018"),
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("74b753b4-c1c2-48ce-a0b8-4f0f0282acfe"),
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("b19a9676-9176-4c1b-b1ab-0c66e3d03055"),
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("31c343d3-42ab-444d-a85b-a979bbd5f9bb"),
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("78714c7f-1c77-4f1a-afe0-ddc90671f6cf"),
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("32291125-2799-4b79-ae44-062e06110f67"),
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("985d9eaf-5f8e-4654-a415-2e055bc31aeb"),
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("ccbc0867-008d-4806-a156-e9caec6bf211"),
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("698b6e49-26fb-44f7-88a3-ca80aed85956"),
                            Code = "CD",
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = new Guid("299344f7-ef67-47bf-b2f6-fa63fbdbc9e9"),
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("09717884-2001-4423-a271-063a13e8c1c2"),
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("1e6eb942-697b-4968-aeac-13c6eb84c351"),
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("117cb649-27c3-4484-b699-9922d4c083c6"),
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("b4494b8d-7559-4338-a42c-b87c770f4f5e"),
                            Code = "TL",
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = new Guid("806d2d05-19cb-4d29-960e-c615123a1488"),
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("68c05edf-24cc-4b9d-97b1-b27b44b5b9ac"),
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("82958f16-9bfb-47a3-a079-13791e7fb508"),
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("a8b49859-e744-4c23-a260-1b31779ecfbb"),
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("865418d5-3f5c-4086-8c9f-e43d8a2282be"),
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("d6ccc625-4f3a-42c3-b244-0716efd940cd"),
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("08329b6f-aa82-40f3-ac33-9e47e8085146"),
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("11d8c100-ba0b-4a59-8ffd-1211d7d2791a"),
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("e9ec6c81-15c0-4c89-b9a2-c525fcc44dbb"),
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("c941443f-bb7a-4cdc-8aec-eb46be347601"),
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("56dd4861-314f-4c74-82c4-cd789dfd601d"),
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("8c774c29-ccd7-4a65-8ca3-7b27aae12947"),
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("d3e9fdc6-3515-4f7f-a093-79413c1cfa02"),
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("1cea87cd-a6ee-4622-ba8d-9f172d1d1192"),
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("43269b30-69af-41f8-99b3-4b672a731c9a"),
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("b38d0a1a-8c38-4151-ba50-f5d0cf1206f0"),
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("3fcb988e-044b-4831-a2ae-bb7540d1dcc9"),
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("141cbdb1-39e2-400d-893f-96343ef422f0"),
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("5214e6b0-27f3-488a-a2cf-945e8c2999db"),
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("4c0a9d77-373f-4218-8295-53522b82ed5c"),
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("8c772d4c-5cb4-4fde-9096-7220f01d5cc2"),
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("83ca6bdc-bb3f-4d13-bfb9-5664835185cd"),
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("8f137454-afa4-442d-b767-389072fbbdaf"),
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("18de0e23-0d1a-485d-b5b5-f668f8707d62"),
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("d3914858-8202-41cc-bfd1-4eee2cbc4571"),
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("2a6b79d7-575f-4ea1-93af-a2f77b608da9"),
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("4f57b105-d9d1-435f-8f9a-ef8b2b3ec2e7"),
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("d6dc1ea7-698c-4551-94db-92061391f072"),
                            Code = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = new Guid("287b0ab6-cd5b-4aee-b145-e4a83408c4d7"),
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("dbfc590d-4526-44c8-9d82-5eab46b58aaa"),
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("d008ed0f-d388-4f26-be12-ba5c00b663ea"),
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("26921024-8997-4563-a773-286649404406"),
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("42079fbc-95b9-4b59-a484-a585ae424eef"),
                            Code = "CI",
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = new Guid("a4bf5a32-3cc1-49d6-8857-947e070b8968"),
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("8893ff1a-0e54-468d-8520-06794dcff8f8"),
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("33601015-237d-459f-8d06-3c84314b2cb1"),
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("0c2ecf58-24e7-4288-925d-6d213745e03e"),
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("da0d0e05-2409-47d7-a58d-cc6257ca5e16"),
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("03a94a4c-2fb1-43b2-92af-f6739ce90610"),
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("b85dc460-611d-449f-b812-01dd9a5663a6"),
                            Code = "XK",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("42e9b722-8e56-4dff-8d07-7aa9a7df8c3a"),
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("db342736-e639-480d-8602-9047dbd50dbb"),
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("3e77de1b-c8b3-4463-bfb0-4513d796e399"),
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("32d675fa-231e-41d8-8292-83c4da5ca7f3"),
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("b8c0fa5b-03e3-4819-962c-98b2d151c187"),
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("a7d839ad-ee9b-4b0e-a40d-c9bfb0fe4107"),
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("f8e99226-68a2-49ca-bcbe-db4c51789d40"),
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("22376a61-3d5a-46a5-8880-1c340429fee0"),
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("27c70cc6-e769-44f7-8210-4b26d4e27a80"),
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("5657de35-3521-4fd8-8d97-30536ff80fd7"),
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("20d62d44-419d-471f-ad79-a9eff2c3c639"),
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("9fd20fa3-c07c-4a23-a03d-c86f9119902d"),
                            Code = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("9c515461-e6b2-41fc-80c1-a51e44e6f20e"),
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("c27dcd7a-2511-4d4d-b139-08c9178b1d63"),
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("1708bb5f-c090-4e1b-9e24-7e37681172db"),
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("5a3cb4c3-652b-46c9-b8b6-7b9fb82bf41c"),
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("7f3c4c5a-9b24-48c4-97d2-d7e73cc8d359"),
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("d1fc04a3-b7e0-469d-a603-f01dfe6dfd4f"),
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("451860dd-282c-4960-aa86-9bbd86ea98d0"),
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = new Guid("3b55ed04-414c-4d35-bb56-baf5c847e2e1"),
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("423a2287-c7b8-43de-9379-17de5d5595c0"),
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("ac69f404-4a8e-411f-a92e-ddec489d477b"),
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("1a744827-2d6b-4bf2-a28d-e979b3d24a5a"),
                            Code = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = new Guid("fc030833-c608-4439-9b50-f5af61810233"),
                            Code = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = new Guid("32686997-1652-46fc-a8d5-24de060a77d9"),
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("12e0d9c2-6a66-4cef-9e1b-a8574b0f46b1"),
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("ccf8ed06-47e9-4bda-b439-8033998ed64d"),
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("8b4cd427-73f6-4248-9af1-a76ad9bd5129"),
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("022fbb7c-98d3-4c4d-bcc6-fd579c00a509"),
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("4668bf50-798c-4aa1-a062-68be6b2e38f0"),
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("25e01b8b-b5be-464e-a4c0-e2a930a836fb"),
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("767e8094-a3e2-4aa2-90a1-f224fae7e23d"),
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("24c51f3d-d697-41d9-a9bb-1af0016fe983"),
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("2a7bddae-8462-4971-affc-a4e6455d7d13"),
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("5631266c-6c8e-43e5-a60e-6d463f50f18c"),
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("c3d6f5ac-cc65-4082-a14e-d184dd5ec1b4"),
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("71636732-cec6-4117-8859-c1fc91ac25b8"),
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("2c400de1-0216-42e2-9ffd-36459920673d"),
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("e8312fc3-9f25-4c38-9e28-ab697faa32ae"),
                            Code = "KP",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = new Guid("9e1acf70-cf9d-426d-a7d6-bfbfa8ac4fe6"),
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("9ce69e78-bd59-490c-9c6d-fca056b1917d"),
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("3d0c339e-9a27-48bc-bc39-903a0c42e09b"),
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("5ffc027e-94fe-4a90-8824-97d51b11da8c"),
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("0e766930-0a45-4673-aec6-9d48e76ca5f2"),
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("9ffaf090-5de2-48b0-a2ef-3ed35e222ea0"),
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("597db181-1dc8-4bf9-861e-288fd3204dc1"),
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("c483356a-d1ad-41c6-90bd-103c81dbcb8f"),
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("d7295b9e-2935-402d-9977-a51e25e8e057"),
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("8df700a2-806a-4d4c-b94b-556762afea63"),
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("7448e95c-afd1-449c-9d52-e5585a88f472"),
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("034bfc4a-3d38-404a-ac8b-077973eb7384"),
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("b19e9714-4425-4b48-8396-bc3ae49d3597"),
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("1850ed1d-0b15-463e-a01d-e97f2ae534a8"),
                            Code = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("64fb5dc9-31f9-4632-a423-d6d2e56326e7"),
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("5633fcf4-0269-4103-907c-57e2c745a857"),
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("7a0347a5-f597-41c4-8646-2693434b8378"),
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("61be9df5-451e-4427-b1c3-09e9f15cc00d"),
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("8053ed0c-9d1a-40fa-a676-a92dea30c31a"),
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("0ec072fc-4239-447c-b9b0-0565bdac0013"),
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("2939a969-b832-4297-8cbe-31044fa84b0f"),
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("ff3c8852-69fb-42f0-9af3-117563b830a1"),
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("31d1760a-6205-4512-a5c7-01f12130a338"),
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("e81d11f9-4af9-4fe4-a402-b93fd30a547f"),
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("f0176a50-8907-4983-b9f3-985e3c76f955"),
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("00351d7a-4ce4-4e96-821d-1582223efad1"),
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("31531b26-1353-4b27-b384-042cc1530b32"),
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("514a172a-3354-4d2d-8976-e88ba5f103e3"),
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("bed93f1d-3c29-42c6-93bc-7fc70dfeea40"),
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("ee25b4de-d2d2-4229-8160-7cc6334f5a6d"),
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("3933bc24-3b21-4668-a948-018e92d9b881"),
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("efe64c25-218b-4154-ad69-70d5e974a954"),
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("f817a731-2890-425a-a3a5-32298a5e96cf"),
                            Code = "KR",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("2ba5cc42-d912-4ce0-a987-c2ae8c58ac6b"),
                            Code = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("95ac27c2-e25f-4bc5-889d-a89e7de314ca"),
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("ffa60634-8665-4aeb-8a6f-eedeccee499d"),
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("35e254de-e2fe-4916-bc7a-e99815016c91"),
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("57de6c23-a109-4f05-af9a-0e09f886e195"),
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("b39d6f63-5e60-4dc6-ad36-b3946a51acc5"),
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = new Guid("7534ac32-26c0-4577-bec9-58d54b357919"),
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("596890c8-febe-410a-8241-b9a4f6953f06"),
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("7ec4f180-a33e-4864-afec-8705e49a5d73"),
                            Code = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = new Guid("d329bb6a-124f-42c8-9f6c-a8f51f181b21"),
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = new Guid("10c0d2ac-8bc4-4a0f-9697-63fe3bc6c0ed"),
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("6f9bb715-8b21-426a-95a6-6ce2d070bc43"),
                            Code = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("c60c21ce-edc0-4518-8772-0333207a87d3"),
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("8d7faa98-916e-408f-b65f-c3b4e3186bf1"),
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("c25b3ced-6b24-4768-8f76-3adf95f355e2"),
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("40a7e84a-f14c-494f-ad8e-6706fd50781e"),
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("9051cfd9-6b17-430a-9abe-a916a834f830"),
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("e6eef489-8cb1-40f9-8f8a-2edc65cff2ac"),
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("6f815b9a-4454-42e7-8a2f-33dd42632d4a"),
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("3bc8d4b7-19aa-4e0c-a7dd-0516ff87c874"),
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("e879f18b-f559-4c23-94c3-3f6785f83b31"),
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("98e68f43-90c2-4107-a75c-ebb33e111124"),
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("ce7a9b74-f411-4c8e-a5a6-2b3c27aaee60"),
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("a563a3d1-3091-4105-809a-d27679e749c9"),
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("12561d10-1453-4839-b060-5ea62428c39b"),
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("19fe01d0-fe84-4b98-9ea1-5ecf632485a6"),
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("0b60f25c-b8e5-4953-9869-6259b45f9721"),
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("437e29af-1b2b-4925-9d87-a25d95f4cda3"),
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("de45c8ba-c2ba-4735-9821-1ea26ef3b457"),
                            Code = "VA",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = new Guid("5baf4eba-3680-4650-9a17-2d2487e06f58"),
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("dfab6a64-72a4-429b-b8ea-5c8bbe4b2fc2"),
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("bb4ba563-b197-4b0e-b003-7efe3b7b1c8a"),
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("280f97fd-f833-499d-bbeb-9e63c1569ee2"),
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("584818d2-9910-49fc-8526-2634d0b05f96"),
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Identity_Models.Models.Friendship", b =>
                {
                    b.Property<Guid>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("User1Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("User2Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("TEXT");

                    b.HasKey("FriendshipId");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Identity_Models.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("CountryId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Identity_Models.Models.Friendship", b =>
                {
                    b.HasOne("Identity_Models.Models.User", "User1")
                        .WithMany("Friendships1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Identity_Models.Models.User", "User2")
                        .WithMany("Friendships2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Identity_Models.Models.User", b =>
                {
                    b.HasOne("Identity_Models.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Identity_Models.Models.User", b =>
                {
                    b.Navigation("Friendships1");

                    b.Navigation("Friendships2");
                });
#pragma warning restore 612, 618
        }
    }
}
