// <auto-generated />
using System;
using Backgammon_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity_DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("Identity_Models.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countrys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18c4dcbd-8640-4a8e-8478-140535d8f4b8"),
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("ecc76640-b267-48a6-86eb-ce614999a6ee"),
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("6dec78a0-772c-4d23-8d3b-b40c71490f94"),
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("c82d16d0-a60a-43c5-9f77-1650035c0481"),
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("384aec82-5dab-4397-9076-9dee2d75ea3b"),
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("d62b3695-63b3-4120-a977-c31967c1544d"),
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("7071d3d6-b4cf-400a-a888-d43eac718d36"),
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("ad353a6f-9520-4c5b-a871-beb77e46726c"),
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("b2482610-2660-45d9-b7c0-e60e37171906"),
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("2483a5c4-baa1-4594-9d59-345a376cd3b6"),
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("602bc458-2596-4105-bf90-6fbaf525fc04"),
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("200b8d48-0893-4072-acaf-d96acd446566"),
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("9163826e-bf38-482e-8025-afb03ca71dab"),
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("a184fb5e-512c-47a5-8659-6d933137e197"),
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("d558138b-06c7-49bb-94a5-a3dd30f6cd49"),
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("bbe682f8-f906-4cb7-9786-ab25a3f18a80"),
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("ea5f5391-8ad3-4056-83f0-2b5fd79fdc6b"),
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("c4bc93b3-576a-4dc9-8159-c5bd271b5434"),
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("8014daef-10e5-4703-8d8c-7a54cc16eaaa"),
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("57c3001d-bb10-4017-8ecd-ac7027c44e95"),
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("f2d31f82-da84-42d2-b4eb-1f662a1cb215"),
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("1f220f4a-7ffb-4802-b7c8-b9fe029ffa47"),
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("202f6c75-46a0-4b04-91b1-401438cb31d1"),
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("5b42422f-20db-4e87-9fff-1a5f87e379b0"),
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("8c43616c-c7a1-4130-aa7b-be329fc67d8a"),
                            Code = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("0980b42e-6508-4535-a966-3d9f769796c5"),
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("5d1d2625-95c5-40a3-b37e-43c7ff101ce0"),
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("933fe465-655f-4b66-96df-e3fd1c591d90"),
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("d59088c7-9863-4f72-8868-b2fb7f8165a9"),
                            Code = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("dc8a5bd6-81b1-47ee-b1c7-caba98969f0e"),
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("aede2370-d8b6-4843-9c74-572a1d9db33b"),
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("2a81010a-bfea-43b3-9ef4-b10a475940af"),
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("d442cb0b-0061-4c84-84f3-3e08ed353b20"),
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("cf16cf70-abcb-4721-b96a-87fff648457f"),
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("19464ce6-cd5f-4f88-b192-107c51479316"),
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("b53ab50a-6dbe-45c6-af56-41f8c169d817"),
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("7a797905-c5da-46d0-ad80-85c51c903b42"),
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("3d9bb8bc-d4cb-4758-8601-3c6483295a19"),
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("51780af8-e55f-4a47-9951-1c7ae1f2e3d1"),
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("2e885738-1981-4e1f-a814-0a9268468639"),
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("ffb82461-0d36-49dc-9b2e-a252202609a0"),
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("18011210-dfd6-401e-aa28-d52ec782c6aa"),
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("bb3d0e6c-0b89-4b4a-802e-290bbbe6ad9f"),
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("d06002b1-4ae2-4c33-a0ce-0f83663405dd"),
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("7077875f-6bd8-42ad-bbc3-e3c79762591b"),
                            Code = "CD",
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = new Guid("8275479a-5ebe-40d9-9a49-a4aaffdb71fe"),
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("72925270-4819-491e-970a-db8daa07d742"),
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("54d6424b-aee2-442a-a756-4dad51d8a773"),
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("0b0b3450-e584-4764-b445-fe2d44fed022"),
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("762e9d7d-75f6-478f-bfb8-20b874d297ae"),
                            Code = "TL",
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = new Guid("f04f3267-2405-4df9-bba9-53498f634140"),
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("767ab7b2-2ffa-4af6-bb07-cf40d64a4b94"),
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("2b91492c-5f44-4048-bdc7-424427cd70b5"),
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("5a368985-9374-4599-93ed-670736cb7996"),
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("bd9bfe5b-1c89-450e-82f0-75ba956abed2"),
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("61b599bf-d512-483a-91f0-702a2b953182"),
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("a45efe3d-d3e9-4c01-8ecc-68d5a57c0652"),
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("a6dd67c6-660e-4489-accd-769643c0e5a0"),
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("002c149d-d7cd-475a-b2f6-ab451eb9e41f"),
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("368d2e22-7594-4107-bfdc-85a75647ba1f"),
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("500ef857-be6f-41e2-8ede-471573f7b2f7"),
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("110c1777-a954-427c-926f-06051aab2640"),
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("30386db6-64b7-4c7b-8a4f-9b328ee0d560"),
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("866b084c-8615-4289-b315-4ccd57d6bd25"),
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("f236fcd9-7ccf-43a7-b4a9-8ea38cdc10a6"),
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("494d2331-8364-40ea-ae87-09b0dcf5c444"),
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("1b56e461-cb9b-4186-927d-50b3c2d0d57c"),
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("0a8d4ca8-8786-4e09-94c2-7e25ce8b34bc"),
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("5acd97b2-c322-4de1-988a-7f268c9350fa"),
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("5de4ce15-dd45-48c9-b0fa-ba2d8b17d733"),
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("3a5161da-0007-4d05-bbf3-4d50141d5b97"),
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("2e68c194-eba2-44b4-ba14-1c7274c043b5"),
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("c4c115d4-84e8-412f-a0f4-74624f912fbe"),
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("a8ff0ec2-720c-4e91-a2d5-50cd96cedbb2"),
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("c2fe3fa6-9e2f-49bb-850a-36b675f2d47a"),
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("c1c1c6cc-7d26-4021-a461-85b60820b7cb"),
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("fecbaff2-f536-4df8-b225-fa26f7e61750"),
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("33517525-1bcc-461c-a753-03334b95e347"),
                            Code = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = new Guid("550a4cdf-a5e1-4a85-a484-a3f2e08bf243"),
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("33a8c1bc-e976-4bf0-81cb-de00150e6ad9"),
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("97b62cc1-3f46-408e-a240-6bd875f8a85a"),
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("18112fa9-10ec-4919-9187-281e635b8c06"),
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("cbfe7c46-4bba-483e-875a-df96c656b1c3"),
                            Code = "CI",
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = new Guid("7dc4cd88-167b-4578-8d61-56260b4df1fb"),
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("6d864aae-6787-4d53-9c9a-b1f1d3a2d862"),
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("d740ce42-6877-4979-a4fa-cd6b630b12b1"),
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("5a43bfd2-b76a-4e10-b3ec-f9d44f8e99dc"),
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("50750ab2-1bbd-4446-8745-fb32c9a27db8"),
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("4d44c1f1-ec76-4f1a-9090-cf680d88ee03"),
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("ee5ff0a7-8d6e-415f-bc33-1693054fee6c"),
                            Code = "XK",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("890aecd2-28c1-482d-bd7a-aadbe92a6325"),
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("e4eafdf5-aa15-466e-a3ab-c3a4020a1073"),
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("26711de2-5ea3-491c-bb0c-e5538950c5ae"),
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("d74b7d27-d8fc-416f-82fa-e8f877d4346f"),
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("c8ce5200-c03e-4564-8ac2-33a09aa5665d"),
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("206c3a29-e323-4976-bb42-ffadd136d4da"),
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("0dc3d79f-acfb-4756-8096-0887fa5e676e"),
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("71d5cdf9-5ee6-4a0c-b0a1-5faa8426f090"),
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("b290e371-5142-4aad-8ad3-62e9d4a6c493"),
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("f0618d17-d37f-421e-a228-ae49c266d19f"),
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("9dc91d9c-f0de-4ba7-a2c0-76134e1f5e91"),
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("3c744cfe-99f2-4266-bbd6-df94d03f34fe"),
                            Code = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("bf6d09ad-d34e-4efd-a69f-84fcfe18aefe"),
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("04be5b0a-981e-4901-b13a-6ab1c3270c41"),
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("54aa0887-f5a6-43c7-af04-b9c8e46d8bb6"),
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("a2d0d92a-5035-4f67-8e23-e782dc02c519"),
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("57f78ec0-058b-4f94-a122-97e1e8751d17"),
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("46628149-0121-41bd-9b53-24486ba1bd12"),
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("e6110b41-383d-4524-82b9-bb0d6f58a73a"),
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = new Guid("d762f85f-3360-46e5-86c7-4ae7922999b1"),
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("ac02a0f9-7f30-4135-9079-23d6c210858c"),
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("c244c58c-8566-4414-b5b7-6e8dd635bc90"),
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("59fd20e3-1f82-471b-a621-0c815f8860df"),
                            Code = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = new Guid("a8a77514-e35b-4ceb-9260-9761c647e484"),
                            Code = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = new Guid("98598d6c-02bd-41e4-8ab6-6cab266635fa"),
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("435f64d0-b1c0-4734-9e12-1909bcd45fb2"),
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("bf2804b6-4c77-4f5d-94ef-dd8ae2347cbe"),
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("4db0cf4a-3f17-4017-afcf-941c6f30fc59"),
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("7a98444b-6e62-4789-9508-69cd1f6664d0"),
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("3013fbf4-de55-4309-a913-521337b6a47b"),
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("c382a078-e9e5-41d1-9bae-784a786b92b8"),
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("1186054b-1e31-4cd8-88a3-f61529d6d545"),
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("7a33fd3c-2637-4b2a-92fb-e34cfb5e6010"),
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("386b45ca-3060-4e19-892a-22acb3ace47a"),
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("29d8cfc7-2cfb-4a27-a784-11cd9989bdce"),
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("b48884aa-341d-4391-9bce-80e11a0a4261"),
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("740641dc-a154-458b-8263-0a398d91fbd3"),
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("80ca4c44-a2c7-4ba5-b4ce-da93b28c057b"),
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("ae8d0f26-3d41-4bef-bc0a-b9ead2990e7a"),
                            Code = "KP",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = new Guid("5770bcc1-7eb1-4127-a640-f53d8b6630ed"),
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("e2f85626-1e7e-462b-b1f3-bf220df7d6a6"),
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("f544f363-78f1-47af-b3f0-7ea184bda461"),
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("0f6c60e0-aaab-491c-9f34-2feed260f4b7"),
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("0c8634e2-7b8d-4c19-a213-09e6cfdecc85"),
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("e2a35270-f478-4975-abae-893a34d2f144"),
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("39c60555-351f-40a5-8f22-8f0882f00e67"),
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("b3ecd218-2982-424e-ad9e-04827b6eee8b"),
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("fa518907-07fe-4f49-9196-0abca14f1b0b"),
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("bc2ea00f-d7c7-4e9a-9b8f-7de6668f31a1"),
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("fe19ec9c-7ea2-4bfe-8c30-6197ac9460fc"),
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("00256718-0645-452f-b892-b7748d4d04bb"),
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("d5c3bbc8-6482-4c98-9a2f-4fe1221c7bf5"),
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("dbe3ea26-7d90-41b3-9fec-961f7fae4e05"),
                            Code = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("1c919bc4-b019-43b4-9bb9-da249306f6a4"),
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("4f0720c3-e3cb-4457-8d0a-47b332baa551"),
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("c1783504-a546-4387-a8e1-10a50303efed"),
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("1898dbf3-c1eb-4050-a953-552bb97f34ed"),
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("5cdb9d5f-2a53-412e-97dd-1149bfdb18ab"),
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("d8b9ee70-2932-4f57-95fd-353c83a672bf"),
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("2026bb6c-aa79-4203-946c-3907ed37eb43"),
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("665a991d-b96d-4eec-9d42-b387616c6d2d"),
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("ae2b8fab-d23b-4c31-bdb5-2817dcfef5e6"),
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("b206b614-2921-4370-b7a7-c6941ec3729f"),
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("5947c494-0db1-403c-9279-057a68590685"),
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("78e4806c-04a7-481b-9894-26db9d9b5f2f"),
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("ccd75e46-623d-42e9-bade-2e9be172628e"),
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("59052215-0e18-40ff-a238-c760350be706"),
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("08e40902-f09a-440b-95d8-c7f74af5e4cb"),
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("68a85cf1-ac4f-49bc-99f1-79fd9631c7e0"),
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("7a131a0e-c101-4461-898b-ebc7c097a444"),
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("29fe781e-1989-44b6-b10f-08a67db2aff5"),
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("b708cc86-419c-4459-a00c-999c160ed80e"),
                            Code = "KR",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("f2d35091-62ae-46a9-a659-872765e3f3b3"),
                            Code = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("82b4c627-9baf-4aed-8de0-b44b91a111be"),
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("5df6461d-b0be-4f14-9d42-b7d370e83aed"),
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("7ee6dad1-f3cd-41e2-ba83-23accf48f3f9"),
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("62ba217f-496d-4d55-bf07-d61fa06dbf0e"),
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("bfc3943f-c380-4c9d-9b8b-988bd67d9bc0"),
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = new Guid("ac687e1e-5f63-4cbc-952b-dfbca6a55b12"),
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("46d871c5-9681-4317-b927-aa78e4ef8356"),
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("08c995e3-1697-4d35-8330-94c9d030dfbd"),
                            Code = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = new Guid("66de0e91-2d02-480f-82f5-9112a36aa8f6"),
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = new Guid("f36a86a3-f586-4ebf-a694-c541234793b5"),
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("2fa1ac81-890d-46c7-ad15-c445936acac6"),
                            Code = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("a32e845c-de98-4858-a50b-8978eef4418d"),
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("88277c30-4e55-4204-b138-6b8e2149a805"),
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("2c220c1d-e4f0-4931-b6c9-1f86082881a8"),
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("ae3b87ec-2cef-4909-9a38-e0fa841ea1bb"),
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("54d833ff-b826-4b7f-b24d-115a589a74fd"),
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("475b1af4-5774-4187-bf53-7d4813b301bd"),
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("fb5f8a20-f2dc-462e-8f84-fe56b4b02798"),
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("b1a89353-2d8d-4888-8f4e-a4f27dd2eca7"),
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("c06d7815-9ed1-408d-8450-4bf4972b9d80"),
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("bfb34f0d-cf01-444b-bc72-b349a1c8778f"),
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("665c321b-5ebf-492d-b1d4-be698c879b2a"),
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("e9412f5d-4dab-49c7-9a84-e30c2503c2f6"),
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("590aea67-1560-43a6-9c45-4fb84663ca97"),
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("0ad65b8d-c346-4436-908e-099b2fde81c0"),
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("22a61788-7f0d-4736-b2eb-89cd2d5335be"),
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("3e9aebce-1fad-4376-96d1-165fc5416897"),
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("8065eced-3562-4888-8da3-5cb91197dde7"),
                            Code = "VA",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = new Guid("31e612fc-33c9-4062-a789-9d9e4ba6ef6f"),
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("d79d19d4-71f2-4cc4-b92a-20e07132e3aa"),
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("3e93e919-3194-473e-b2bb-f0a7be99289d"),
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("5827ee0d-fd4f-4476-8482-5abbec399041"),
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("fc784679-cc77-493d-bdc0-054378ed39a7"),
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Identity_Models.Models.Friendship", b =>
                {
                    b.Property<Guid>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecieverId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.HasKey("FriendshipId");

                    b.HasIndex("RecieverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Identity_Models.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("CountryId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Identity_Models.Models.Friendship", b =>
                {
                    b.HasOne("Identity_Models.Models.User", "Reciever")
                        .WithMany("Friendships2")
                        .HasForeignKey("RecieverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Identity_Models.Models.User", "Sender")
                        .WithMany("Friendships1")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reciever");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Identity_Models.Models.User", b =>
                {
                    b.HasOne("Identity_Models.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Identity_Models.Models.User", b =>
                {
                    b.Navigation("Friendships1");

                    b.Navigation("Friendships2");
                });
#pragma warning restore 612, 618
        }
    }
}
